name: Vitest Tests

# Controls when the workflow will run
on:
    # Triggers the workflow on pull requests to dev or main
    pull_request:
        branches: [main, dev]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    VITE_API_KEY: ${{ secrets.VITE_API_KEY_DEV }}
    VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN_DEV }}
    VITE_DATABASE_URL: ${{ secrets.VITE_DATABASE_URL_DEV }}
    VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID_DEV }}
    VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET_DEV }}
    VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID_DEV }}
    VITE_APP_ID: ${{ secrets.VITE_APP_ID_DEV }}

jobs:
    vitest:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Install Modules
              run: npm ci
            - name: Run Vitest
              run: npm run test
